language: cpp
sudo: required
dist: trusty

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5  libexpat1-dev libxml-parser-perl lcov
      env: COMPILER=g++-5

before_install:
  - pip install --user cpp-coveralls
  - gem install coveralls-lcov
  - lcov --version

install:
  # install latest LCOV (1.10 still has perl error)
  - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
  - tar xf lcov_1.11.orig.tar.gz
  - sudo make -C lcov-1.11/ install

script:
  - pushd build/tizen/
  - autoreconf --install
  - export CXXFLAGS="--coverage "
  - export LD_LIBRARY_PATH=/usr/local/lib
  - ./configure --enable-profile=UBUNTU --enable-gles=20 --enable-debug
  - make -j7 
  - sudo make install
  - popd
  - pushd automated-tests/
  - ./build.sh
  - ./execute.sh
  - ./coverage.sh -n
  - popd
  
after_success:
  - find . -name dali.info -exec sh -c "cat {} >> cov.info" \;
  - coveralls-lcov --repo-token ${COVERALLS_REPO_TOKEN} cov.info # uploads to coveralls
  # - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
